### ISSUE TITLE
Get undefined dates in February

### ISSUE THREAD

**Issue by bbkiwi** [priyank-p/simplepicker#11]
Nice code. Using a cut down version in a ESP8266 project. Noted that not working
for the month of February. It is because is spelled wrong. 
In dist/simplepicker.js
`e.exports={monthTracker:n,months:["January","Febuary",`
should be 
`e.exports={monthTracker:n,months:["January","February",`

**Comment by priyank-p** [comment]
@bbkiwi Thanks for the report! That indeed seems to be a typo. I am curious to know what breaks because of this typo. I tried this on Chrome and it works just fine so I guess a browser compatibility issue.

Either way, I will try to get a release out with a fix today.

**Comment by priyank-p** [comment]
Also, what do you mean by the "cut down version in a ESP8266 project"?

**Comment by priyank-p** [comment]
This fix is published to npm as v2.0.1. Thanks, @bbkiwi for the bug report.

**Comment by bbkiwi** [comment]
Hi Priyank, I responded via email to the above, but I don't think it's gone thru, so I'll put comments here again.

  With the spelling error, it works on my ipad (safari) except February is spelled incorrectly. However in FF 72.0.2 (64bit) it opens correctly but when the day is changed see screen shot.

![openinFF](https://user-images.githubusercontent.com/3452753/74006591-00e99a00-49e1-11ea-91a5-10bdb518d85e.png)
![changedayFF](https://user-images.githubusercontent.com/3452753/74006596-03e48a80-49e1-11ea-997a-528f5e38787f.png)

The ESP8266 project serves up files here:
https://github.com/bbkiwi/LEDClock/tree/useMulti/data

I'm not very familiar with JavaScript and npm. So I just grabbed the files from dist in your repo.
I don't understand completely how you build everything. The new commit changes lib/date-util.ts
but files in dist have also been changed, but dont show up in the diff. 

Cheers, Bill

**Comment by priyank-p** [comment]
Hello Bill, the reason the change does not show in the diff is that I update the dist folder during a new release. If you check master the dist should have the correct spelling. See 71d7dc88fa1c0032416aaa4c02069085bbc26d89.

The build process is simple. First, we compile typescript to javascript. We use typescript because it provides type checking. Next, we run it through babel to ensure somewhat older browsers can handle new features that are being used. Lastly, it is minified so it takes up fewer bytes!

The build tool we use is Webpack which is pretty common to build the frontend assets.

**Comment by priyank-p** [comment]
In the GitHub project you listed, here is the link showing the correct month in the dist folder: https://github.com/bbkiwi/LEDClock/blob/useMulti/data/dist/simplepicker.js#L116, which means it should work fine now.
